version: 0.0
os: linux
files:
  - source: /
    destination: /opt/myapp
permissions:
  - object: /opt/myapp
    owner: ec2-user
    group: ec2-user
    mode: 755
hooks:
  BeforeInstall:
    - location: scripts/clean_old.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 900
      runas: root
  ApplicationStart:
    - location: scripts/restart_service.sh
      timeout: 300
      runas: root
  ValidateService:
    - location: scripts/health_check.sh
      timeout: 60
      runas: root
